/*
	Master UI Resource File

#include "common.hpp"
#include "shop_items.hpp"
#include "gang.hpp"
#include "impound.hpp"
#include "bank.hpp"
#include "veh_shop.hpp"
#include "shops.hpp"
#include "hud_stats.hpp"
#include "admin_menu.hpp"
#include "wanted_list.hpp"
#include "ticket.hpp"
#include "clothing.hpp"
#include "trunk.hpp"
#include "spawnSelection.hpp"
#include "chop_shop.hpp"
#include "pInteraction.hpp"
#include "deathScreen.hpp"
#include "vehicleShop.hpp"
#include "settings.hpp"
#include "federalReserve.hpp"
#include "compensate.hpp"
#include "FuelStat.hpp"
#include "newsStation.hpp"
//Travis's Custom Phone
#include "CustomPhone\Dialog\player_inv.hpp"
#include "player_menu.hpp"
#include "key_chain.hpp"
#include "moves_menu.hpp"
#include "cell_phone.hpp"
*/
/*
	Master UI Resource File
*/
#include "common.hpp"
#include "shop_items.hpp"
#include "player_inv.hpp"
#include "gang.hpp"
#include "key_chain.hpp"
#include "impound.hpp"
#include "bank.hpp"
#include "veh_shop.hpp"
#include "shops.hpp"
#include "hud_stats.hpp"
#include "admin_menu.hpp"
#include "cell_phone.hpp"
#include "anoncell_phone.hpp"
#include "wanted_list.hpp"
#include "ticket.hpp"
#include "clothing.hpp"
#include "trunk.hpp"
#include "spawnSelection.hpp"
#include "chop_shop.hpp"
#include "pInteraction.hpp"
#include "deathScreen.hpp"
#include "vehicleShop.hpp"
#include "settings.hpp"
#include "federalReserve.hpp"
#include "compensate.hpp"
#include "FuelStat.hpp"
#include "dynmarket_changeprice.hpp"
#include "dynmarket_prices.hpp"
#include "craft.hpp"//Crafting